### ISSUE TITLE
question about neovim config

### ISSUE THREAD

**Issue by max397574** [xiyaowong/dotfiles#1]
ik this isn't your neovim config
but ig this is where it makes the most sense to reach you @xiyaowong 
I got a question about something you posted because `winbar` now got merged.
Could you share the config for this:
https://github.com/neovim/neovim/pull/17336#issuecomment-1047795777
?
edit:
nvim-gps?

**Comment by xiyaowong** [comment]
https://github.com/xiyaowong/coc-symbol-line
